server:
  port: 8904
eureka:
  client:
    service-url:
       defauleZone: http://192.168.96.1:8761/eureka/,http://192.168.96.1:8762/eureka/,
spring:
  application:
    name: zuul

zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: feign
  ribbon: #默认懒加载，第一次请求容易超时
    ReadTimeout: 6000     #超时时间
    ConnectTimeout: 3000 #
    eager-load: #饥饿加载
      enabled: true
      clients: feign